//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBodBusiness.SoftWSUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", ConfigurationName="SoftWSUsuario.Usuario")]
    public interface Usuario {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/insertarUsuarioRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/insertarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.insertarUsuarioResponse insertarUsuario(SoftBodBusiness.SoftWSUsuario.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/insertarUsuarioRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/insertarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.insertarUsuarioResponse> insertarUsuarioAsync(SoftBodBusiness.SoftWSUsuario.insertarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/modificarUsuarioRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/modificarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.modificarUsuarioResponse modificarUsuario(SoftBodBusiness.SoftWSUsuario.modificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/modificarUsuarioRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/modificarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.modificarUsuarioResponse> modificarUsuarioAsync(SoftBodBusiness.SoftWSUsuario.modificarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosInactivosRequ" +
            "est", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosInactivosResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosResponse listarUsuariosInactivos(SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosInactivosRequ" +
            "est", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosInactivosResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosResponse> listarUsuariosInactivosAsync(SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerCuentaUsuarioRequest" +
            "", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerCuentaUsuarioRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioResponse obtenerCuentaUsuario(SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerCuentaUsuarioRequest" +
            "", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerCuentaUsuarioRespons" +
            "e")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioResponse> obtenerCuentaUsuarioAsync(SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerUsuarioPorIdRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerUsuarioPorIdResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdResponse obtenerUsuarioPorId(SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerUsuarioPorIdRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerUsuarioPorIdResponse" +
            "")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdResponse> obtenerUsuarioPorIdAsync(SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/eliminarLogicoUsuarioReques" +
            "t", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/eliminarLogicoUsuarioRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioResponse eliminarLogicoUsuario(SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/eliminarLogicoUsuarioReques" +
            "t", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/eliminarLogicoUsuarioRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioResponse> eliminarLogicoUsuarioAsync(SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarTodosUsuariosRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarTodosUsuariosResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosResponse listarTodosUsuarios(SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarTodosUsuariosRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarTodosUsuariosResponse" +
            "")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosResponse> listarTodosUsuariosAsync(SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerUsuarioPorCorreoRequ" +
            "est", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerUsuarioPorCorreoResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoResponse obtenerUsuarioPorCorreo(SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerUsuarioPorCorreoRequ" +
            "est", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/obtenerUsuarioPorCorreoResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoResponse> obtenerUsuarioPorCorreoAsync(SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosActivosReques" +
            "t", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosActivosRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosResponse listarUsuariosActivos(SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosActivosReques" +
            "t", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosActivosRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosResponse> listarUsuariosActivosAsync(SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosPorNombreParc" +
            "ialRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosPorNombreParc" +
            "ialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialResponse listarUsuariosPorNombreParcial(SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosPorNombreParc" +
            "ialRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Usuario/listarUsuariosPorNombreParc" +
            "ialResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialResponse> listarUsuariosPorNombreParcialAsync(SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            this.usuario = usuario;
            this.correo = correo;
            this.tipoUsuarios = tipoUsuarios;
            this.contrasenha = contrasenha;
            this.nombre = nombre;
            this.telefono = telefono;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuarioResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarUsuario", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usuarioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public modificarUsuarioRequest() {
        }
        
        public modificarUsuarioRequest(int usuarioId, string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            this.usuarioId = usuarioId;
            this.usuario = usuario;
            this.correo = correo;
            this.tipoUsuarios = tipoUsuarios;
            this.contrasenha = contrasenha;
            this.nombre = nombre;
            this.telefono = telefono;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarUsuarioResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarUsuarioResponse() {
        }
        
        public modificarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string contrasenhaField;
        
        private string correoField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private tipoUsuario tipoUsuariosField;
        
        private bool tipoUsuariosFieldSpecified;
        
        private string usuarioField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoUsuario tipoUsuarios {
            get {
                return this.tipoUsuariosField;
            }
            set {
                this.tipoUsuariosField = value;
                this.RaisePropertyChanged("tipoUsuarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuariosSpecified {
            get {
                return this.tipoUsuariosFieldSpecified;
            }
            set {
                this.tipoUsuariosFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuariosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        OPERARIO,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosInactivos", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosInactivosRequest {
        
        public listarUsuariosInactivosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosInactivosResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosInactivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO[] @return;
        
        public listarUsuariosInactivosResponse() {
        }
        
        public listarUsuariosInactivosResponse(SoftBodBusiness.SoftWSUsuario.usuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentaUsuario", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        public obtenerCuentaUsuarioRequest() {
        }
        
        public obtenerCuentaUsuarioRequest(string correo, string contrasenha) {
            this.correo = correo;
            this.contrasenha = contrasenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentaUsuarioResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO @return;
        
        public obtenerCuentaUsuarioResponse() {
        }
        
        public obtenerCuentaUsuarioResponse(SoftBodBusiness.SoftWSUsuario.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUsuarioPorId", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUsuarioPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usuarioId;
        
        public obtenerUsuarioPorIdRequest() {
        }
        
        public obtenerUsuarioPorIdRequest(int usuarioId) {
            this.usuarioId = usuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUsuarioPorIdResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUsuarioPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO @return;
        
        public obtenerUsuarioPorIdResponse() {
        }
        
        public obtenerUsuarioPorIdResponse(SoftBodBusiness.SoftWSUsuario.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarLogicoUsuario", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarLogicoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usuarioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public eliminarLogicoUsuarioRequest() {
        }
        
        public eliminarLogicoUsuarioRequest(int usuarioId, string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            this.usuarioId = usuarioId;
            this.usuario = usuario;
            this.correo = correo;
            this.tipoUsuarios = tipoUsuarios;
            this.contrasenha = contrasenha;
            this.nombre = nombre;
            this.telefono = telefono;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarLogicoUsuarioResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarLogicoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarLogicoUsuarioResponse() {
        }
        
        public eliminarLogicoUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosUsuarios", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosUsuariosRequest {
        
        public listarTodosUsuariosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosUsuariosResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO[] @return;
        
        public listarTodosUsuariosResponse() {
        }
        
        public listarTodosUsuariosResponse(SoftBodBusiness.SoftWSUsuario.usuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUsuarioPorCorreo", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUsuarioPorCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailUser;
        
        public obtenerUsuarioPorCorreoRequest() {
        }
        
        public obtenerUsuarioPorCorreoRequest(string emailUser) {
            this.emailUser = emailUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUsuarioPorCorreoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUsuarioPorCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO @return;
        
        public obtenerUsuarioPorCorreoResponse() {
        }
        
        public obtenerUsuarioPorCorreoResponse(SoftBodBusiness.SoftWSUsuario.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosActivos", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosActivosRequest {
        
        public listarUsuariosActivosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosActivosResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosActivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO[] @return;
        
        public listarUsuariosActivosResponse() {
        }
        
        public listarUsuariosActivosResponse(SoftBodBusiness.SoftWSUsuario.usuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosPorNombreParcial", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosPorNombreParcialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUser;
        
        public listarUsuariosPorNombreParcialRequest() {
        }
        
        public listarUsuariosPorNombreParcialRequest(string nombreUser) {
            this.nombreUser = nombreUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosPorNombreParcialResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosPorNombreParcialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO[] @return;
        
        public listarUsuariosPorNombreParcialResponse() {
        }
        
        public listarUsuariosPorNombreParcialResponse(SoftBodBusiness.SoftWSUsuario.usuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioChannel : SoftBodBusiness.SoftWSUsuario.Usuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<SoftBodBusiness.SoftWSUsuario.Usuario>, SoftBodBusiness.SoftWSUsuario.Usuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.insertarUsuarioResponse SoftBodBusiness.SoftWSUsuario.Usuario.insertarUsuario(SoftBodBusiness.SoftWSUsuario.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public int insertarUsuario(string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            SoftBodBusiness.SoftWSUsuario.insertarUsuarioRequest inValue = new SoftBodBusiness.SoftWSUsuario.insertarUsuarioRequest();
            inValue.usuario = usuario;
            inValue.correo = correo;
            inValue.tipoUsuarios = tipoUsuarios;
            inValue.contrasenha = contrasenha;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            inValue.activo = activo;
            SoftBodBusiness.SoftWSUsuario.insertarUsuarioResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).insertarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.insertarUsuarioResponse> SoftBodBusiness.SoftWSUsuario.Usuario.insertarUsuarioAsync(SoftBodBusiness.SoftWSUsuario.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.insertarUsuarioResponse> insertarUsuarioAsync(string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            SoftBodBusiness.SoftWSUsuario.insertarUsuarioRequest inValue = new SoftBodBusiness.SoftWSUsuario.insertarUsuarioRequest();
            inValue.usuario = usuario;
            inValue.correo = correo;
            inValue.tipoUsuarios = tipoUsuarios;
            inValue.contrasenha = contrasenha;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            inValue.activo = activo;
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.modificarUsuarioResponse SoftBodBusiness.SoftWSUsuario.Usuario.modificarUsuario(SoftBodBusiness.SoftWSUsuario.modificarUsuarioRequest request) {
            return base.Channel.modificarUsuario(request);
        }
        
        public int modificarUsuario(int usuarioId, string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            SoftBodBusiness.SoftWSUsuario.modificarUsuarioRequest inValue = new SoftBodBusiness.SoftWSUsuario.modificarUsuarioRequest();
            inValue.usuarioId = usuarioId;
            inValue.usuario = usuario;
            inValue.correo = correo;
            inValue.tipoUsuarios = tipoUsuarios;
            inValue.contrasenha = contrasenha;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            inValue.activo = activo;
            SoftBodBusiness.SoftWSUsuario.modificarUsuarioResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).modificarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.modificarUsuarioResponse> SoftBodBusiness.SoftWSUsuario.Usuario.modificarUsuarioAsync(SoftBodBusiness.SoftWSUsuario.modificarUsuarioRequest request) {
            return base.Channel.modificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.modificarUsuarioResponse> modificarUsuarioAsync(int usuarioId, string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            SoftBodBusiness.SoftWSUsuario.modificarUsuarioRequest inValue = new SoftBodBusiness.SoftWSUsuario.modificarUsuarioRequest();
            inValue.usuarioId = usuarioId;
            inValue.usuario = usuario;
            inValue.correo = correo;
            inValue.tipoUsuarios = tipoUsuarios;
            inValue.contrasenha = contrasenha;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            inValue.activo = activo;
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).modificarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosResponse SoftBodBusiness.SoftWSUsuario.Usuario.listarUsuariosInactivos(SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosRequest request) {
            return base.Channel.listarUsuariosInactivos(request);
        }
        
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO[] listarUsuariosInactivos() {
            SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosRequest inValue = new SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosRequest();
            SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).listarUsuariosInactivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosResponse> SoftBodBusiness.SoftWSUsuario.Usuario.listarUsuariosInactivosAsync(SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosRequest request) {
            return base.Channel.listarUsuariosInactivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosResponse> listarUsuariosInactivosAsync() {
            SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosRequest inValue = new SoftBodBusiness.SoftWSUsuario.listarUsuariosInactivosRequest();
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).listarUsuariosInactivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioResponse SoftBodBusiness.SoftWSUsuario.Usuario.obtenerCuentaUsuario(SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioRequest request) {
            return base.Channel.obtenerCuentaUsuario(request);
        }
        
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO obtenerCuentaUsuario(string correo, string contrasenha) {
            SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioRequest inValue = new SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioRequest();
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).obtenerCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioResponse> SoftBodBusiness.SoftWSUsuario.Usuario.obtenerCuentaUsuarioAsync(SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioRequest request) {
            return base.Channel.obtenerCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioResponse> obtenerCuentaUsuarioAsync(string correo, string contrasenha) {
            SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioRequest inValue = new SoftBodBusiness.SoftWSUsuario.obtenerCuentaUsuarioRequest();
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).obtenerCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdResponse SoftBodBusiness.SoftWSUsuario.Usuario.obtenerUsuarioPorId(SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdRequest request) {
            return base.Channel.obtenerUsuarioPorId(request);
        }
        
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO obtenerUsuarioPorId(int usuarioId) {
            SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdRequest inValue = new SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdRequest();
            inValue.usuarioId = usuarioId;
            SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).obtenerUsuarioPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdResponse> SoftBodBusiness.SoftWSUsuario.Usuario.obtenerUsuarioPorIdAsync(SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdRequest request) {
            return base.Channel.obtenerUsuarioPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdResponse> obtenerUsuarioPorIdAsync(int usuarioId) {
            SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdRequest inValue = new SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorIdRequest();
            inValue.usuarioId = usuarioId;
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).obtenerUsuarioPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioResponse SoftBodBusiness.SoftWSUsuario.Usuario.eliminarLogicoUsuario(SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioRequest request) {
            return base.Channel.eliminarLogicoUsuario(request);
        }
        
        public int eliminarLogicoUsuario(int usuarioId, string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioRequest inValue = new SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioRequest();
            inValue.usuarioId = usuarioId;
            inValue.usuario = usuario;
            inValue.correo = correo;
            inValue.tipoUsuarios = tipoUsuarios;
            inValue.contrasenha = contrasenha;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            inValue.activo = activo;
            SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).eliminarLogicoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioResponse> SoftBodBusiness.SoftWSUsuario.Usuario.eliminarLogicoUsuarioAsync(SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioRequest request) {
            return base.Channel.eliminarLogicoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioResponse> eliminarLogicoUsuarioAsync(int usuarioId, string usuario, string correo, string tipoUsuarios, string contrasenha, string nombre, string telefono, bool activo) {
            SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioRequest inValue = new SoftBodBusiness.SoftWSUsuario.eliminarLogicoUsuarioRequest();
            inValue.usuarioId = usuarioId;
            inValue.usuario = usuario;
            inValue.correo = correo;
            inValue.tipoUsuarios = tipoUsuarios;
            inValue.contrasenha = contrasenha;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            inValue.activo = activo;
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).eliminarLogicoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosResponse SoftBodBusiness.SoftWSUsuario.Usuario.listarTodosUsuarios(SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosRequest request) {
            return base.Channel.listarTodosUsuarios(request);
        }
        
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO[] listarTodosUsuarios() {
            SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosRequest inValue = new SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosRequest();
            SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).listarTodosUsuarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosResponse> SoftBodBusiness.SoftWSUsuario.Usuario.listarTodosUsuariosAsync(SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosRequest request) {
            return base.Channel.listarTodosUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosResponse> listarTodosUsuariosAsync() {
            SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosRequest inValue = new SoftBodBusiness.SoftWSUsuario.listarTodosUsuariosRequest();
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).listarTodosUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoResponse SoftBodBusiness.SoftWSUsuario.Usuario.obtenerUsuarioPorCorreo(SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoRequest request) {
            return base.Channel.obtenerUsuarioPorCorreo(request);
        }
        
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO obtenerUsuarioPorCorreo(string emailUser) {
            SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoRequest inValue = new SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoRequest();
            inValue.emailUser = emailUser;
            SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).obtenerUsuarioPorCorreo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoResponse> SoftBodBusiness.SoftWSUsuario.Usuario.obtenerUsuarioPorCorreoAsync(SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoRequest request) {
            return base.Channel.obtenerUsuarioPorCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoResponse> obtenerUsuarioPorCorreoAsync(string emailUser) {
            SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoRequest inValue = new SoftBodBusiness.SoftWSUsuario.obtenerUsuarioPorCorreoRequest();
            inValue.emailUser = emailUser;
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).obtenerUsuarioPorCorreoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosResponse SoftBodBusiness.SoftWSUsuario.Usuario.listarUsuariosActivos(SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosRequest request) {
            return base.Channel.listarUsuariosActivos(request);
        }
        
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO[] listarUsuariosActivos() {
            SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosRequest inValue = new SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosRequest();
            SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).listarUsuariosActivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosResponse> SoftBodBusiness.SoftWSUsuario.Usuario.listarUsuariosActivosAsync(SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosRequest request) {
            return base.Channel.listarUsuariosActivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosResponse> listarUsuariosActivosAsync() {
            SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosRequest inValue = new SoftBodBusiness.SoftWSUsuario.listarUsuariosActivosRequest();
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).listarUsuariosActivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialResponse SoftBodBusiness.SoftWSUsuario.Usuario.listarUsuariosPorNombreParcial(SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialRequest request) {
            return base.Channel.listarUsuariosPorNombreParcial(request);
        }
        
        public SoftBodBusiness.SoftWSUsuario.usuarioDTO[] listarUsuariosPorNombreParcial(string nombreUser) {
            SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialRequest inValue = new SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialRequest();
            inValue.nombreUser = nombreUser;
            SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialResponse retVal = ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).listarUsuariosPorNombreParcial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialResponse> SoftBodBusiness.SoftWSUsuario.Usuario.listarUsuariosPorNombreParcialAsync(SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialRequest request) {
            return base.Channel.listarUsuariosPorNombreParcialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialResponse> listarUsuariosPorNombreParcialAsync(string nombreUser) {
            SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialRequest inValue = new SoftBodBusiness.SoftWSUsuario.listarUsuariosPorNombreParcialRequest();
            inValue.nombreUser = nombreUser;
            return ((SoftBodBusiness.SoftWSUsuario.Usuario)(this)).listarUsuariosPorNombreParcialAsync(inValue);
        }
    }
}
