IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TA_PROG3')
BEGIN
    CREATE DATABASE TA_PROG3;
END
GO

USE TA_PROG3;
GO

IF OBJECT_ID('BOD_DETALLE_VENTA', 'U') IS NOT NULL DROP TABLE BOD_DETALLE_VENTA;
IF OBJECT_ID('BOD_DETALLE_DEVOLUCION', 'U') IS NOT NULL DROP TABLE BOD_DETALLE_DEVOLUCION;
IF OBJECT_ID('BOD_VENTAS_FIADAS', 'U') IS NOT NULL DROP TABLE BOD_VENTAS_FIADAS;
IF OBJECT_ID('BOD_REGISTRO_PAGOS_FIADOS', 'U') IS NOT NULL DROP TABLE BOD_REGISTRO_PAGOS_FIADOS;
IF OBJECT_ID('BOD_HISTORIAL_OPERACIONES', 'U') IS NOT NULL DROP TABLE BOD_HISTORIAL_OPERACIONES;
IF OBJECT_ID('BOD_VENTAS', 'U') IS NOT NULL DROP TABLE BOD_VENTAS;
IF OBJECT_ID('BOD_DEVOLUCION', 'U') IS NOT NULL DROP TABLE BOD_DEVOLUCION;
IF OBJECT_ID('BOD_CLIENTE_AL_FIADO', 'U') IS NOT NULL DROP TABLE BOD_CLIENTE_AL_FIADO;
IF OBJECT_ID('BOD_PRODUCTO', 'U') IS NOT NULL DROP TABLE BOD_PRODUCTO;
IF OBJECT_ID('BOD_RAZON_DEVOLUCION', 'U') IS NOT NULL DROP TABLE BOD_RAZON_DEVOLUCION;
IF OBJECT_ID('BOD_CATEGORIA', 'U') IS NOT NULL DROP TABLE BOD_CATEGORIA;
IF OBJECT_ID('BOD_USUARIO', 'U') IS NOT NULL DROP TABLE BOD_USUARIO;
GO

CREATE TABLE BOD_CATEGORIA (
  CATEGORIA_ID INT IDENTITY(1,1) NOT NULL,
  DESCRIPCION VARCHAR(60) NOT NULL,
  PRIMARY KEY (CATEGORIA_ID),
  CONSTRAINT DESCRIPCION_UNIQUE UNIQUE (DESCRIPCION)
);
GO

CREATE TABLE BOD_CLIENTE_AL_FIADO (
  CLIENTE_ID INT IDENTITY(1,1) NOT NULL,
  ALIAS VARCHAR(40) NOT NULL,
  NOMBRE VARCHAR(60) NOT NULL,
  TELEFONO VARCHAR(9) NOT NULL,
  FECHA_DE_PAGO DATE NOT NULL,
  ACTIVO TINYINT NOT NULL,
  MONTO_DEUDA DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (CLIENTE_ID),
  CONSTRAINT ALIAS_UNIQUE UNIQUE (ALIAS)
);
GO

CREATE TABLE BOD_RAZON_DEVOLUCION (
  RAZON_DEVOLUCION_ID INT IDENTITY(1,1) NOT NULL,
  DESCRIPCION VARCHAR(60) NOT NULL,
  PRIMARY KEY (RAZON_DEVOLUCION_ID),
  CONSTRAINT DESCRIPCION_UNIQUE_RAZON UNIQUE (DESCRIPCION)
);
GO

CREATE TABLE BOD_PRODUCTO (
  PRODUCTO_ID INT IDENTITY(1,1) NOT NULL,
  CATEGORIA_ID INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
  UNIDAD_MEDIDA VARCHAR(10) NOT NULL CHECK (UNIDAD_MEDIDA IN ('KILOGRAMO','LITRO','UNIDAD')),
  STOCK INT NOT NULL,
  STOCK_MINIMO INT NOT NULL,
  ACTIVO TINYINT NOT NULL,
  PRIMARY KEY (PRODUCTO_ID),
  CONSTRAINT fk_BOD_PRODUCTO_BOD_CATEGORIA1 FOREIGN KEY (CATEGORIA_ID) REFERENCES BOD_CATEGORIA (CATEGORIA_ID)
);
GO

CREATE TABLE BOD_USUARIO (
  USUARIO_ID INT IDENTITY(1,1) NOT NULL,
  USUARIO VARCHAR(30) NOT NULL,
  TIPO_USUARIOS VARCHAR(20) NOT NULL CHECK (TIPO_USUARIOS IN ('ADMINISTRADOR','OPERARIO')),
  CORREO VARCHAR(45) NOT NULL,
  CONTRASENHA VARCHAR(30) NOT NULL,
  NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
  TELEFONO_USUARIO VARCHAR(9) NOT NULL,
  ACTIVO_USUARIO TINYINT NOT NULL,
  PRIMARY KEY (USUARIO_ID),
  CONSTRAINT USUARIO_OPERARIO_UNIQUE UNIQUE (USUARIO)
);
GO

CREATE TABLE BOD_VENTAS (
  VENTA_ID INT IDENTITY(1,1) NOT NULL,
  TOTAL DECIMAL(10,2) NOT NULL,
  METODO_PAGO VARCHAR(20) NOT NULL CHECK (METODO_PAGO IN ('EFECTIVO','TRANSFERENCIA','FIADO')),
  FECHA DATETIME NOT NULL,
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY (VENTA_ID),
  CONSTRAINT fk_BOD_VENTAS_BOD_USUARIO1 FOREIGN KEY (USUARIO_ID) REFERENCES BOD_USUARIO (USUARIO_ID)
);
GO

CREATE TABLE BOD_DEVOLUCION (
  DEVOLUCION_ID INT IDENTITY(1,1) NOT NULL,
  TOTAL DECIMAL(10,2) NOT NULL,
  FECHA DATETIME NOT NULL,
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY (DEVOLUCION_ID),
  CONSTRAINT fk_BOD_DEVOLUCION_BOD_USUARIO1 FOREIGN KEY (USUARIO_ID) REFERENCES BOD_USUARIO (USUARIO_ID)
);
GO

CREATE TABLE BOD_DETALLE_DEVOLUCION (
  DEVOLUCION_ID INT NOT NULL,
  PRODUCTO_ID INT NOT NULL,
  SUBTOTAL DECIMAL(10,2) NOT NULL,
  CANTIDAD INT NOT NULL,
  RAZON_DEVOLUCION_ID INT NOT NULL,
  PRIMARY KEY (DEVOLUCION_ID, PRODUCTO_ID),
  CONSTRAINT fk_BOD_DETALLE_DEVOLUCION_BOD_RAZON_DEVOLUCION1 FOREIGN KEY (RAZON_DEVOLUCION_ID) REFERENCES BOD_RAZON_DEVOLUCION (RAZON_DEVOLUCION_ID),
  CONSTRAINT fk_BOD_DETALLE_FIADO_BOD_DEVOLUCION1 FOREIGN KEY (DEVOLUCION_ID) REFERENCES BOD_DEVOLUCION (DEVOLUCION_ID),
  CONSTRAINT fk_BOD_DETALLE_FIADO_BOD_PRODUCTO1 FOREIGN KEY (PRODUCTO_ID) REFERENCES BOD_PRODUCTO (PRODUCTO_ID)
);
GO

CREATE TABLE BOD_DETALLE_VENTA (
  VENTA_ID INT NOT NULL,
  PRODUCTO_ID INT NOT NULL,
  SUBTOTAL DECIMAL(10,2) NOT NULL,
  CANTIDAD INT NOT NULL,
  PRIMARY KEY (VENTA_ID, PRODUCTO_ID),
  CONSTRAINT fk_BOD_DETALLE_VENTA_BOD_PRODUCTO1 FOREIGN KEY (PRODUCTO_ID) REFERENCES BOD_PRODUCTO (PRODUCTO_ID),
  CONSTRAINT fk_BOD_DETALLE_VENTA_BOD_VENTAS1 FOREIGN KEY (VENTA_ID) REFERENCES BOD_VENTAS (VENTA_ID)
);
GO

CREATE TABLE BOD_HISTORIAL_OPERACIONES (
  OPERACION_ID INT IDENTITY(1,1) NOT NULL,
  TABLA_AFECTADA VARCHAR(60) NOT NULL,
  OPERACION VARCHAR(20) NOT NULL CHECK (OPERACION IN ('INSERCION','MODIFICACION','ELIMINACION','CONSULTAR')),
  FECHA_HORA DATETIME NOT NULL,
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY (OPERACION_ID),
  CONSTRAINT OPERACION_ID_UNIQUE UNIQUE (OPERACION_ID),
  CONSTRAINT fk_BOD_HISTORIAL_OPERACIONES_BOD_USUARIO1 FOREIGN KEY (USUARIO_ID) REFERENCES BOD_USUARIO (USUARIO_ID)
);
GO

CREATE TABLE BOD_REGISTRO_PAGOS_FIADOS (
  PAGO_ID INT IDENTITY(1,1) NOT NULL,
  USUARIO_ID INT NOT NULL,
  CLIENTE_ID INT NOT NULL,
  FECHA DATETIME NOT NULL,
  METODO_PAGO VARCHAR(20) NOT NULL CHECK (METODO_PAGO IN ('EFECTIVO','TRANSFERENCIA')),
  MONTO DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (PAGO_ID),
  CONSTRAINT fk_BOD_REGISTRO_PAGOS_FIADOS_BOD_CLIENTE_AL_FIADO1 FOREIGN KEY (CLIENTE_ID) REFERENCES BOD_CLIENTE_AL_FIADO (CLIENTE_ID),
  CONSTRAINT fk_BOD_REGISTRO_PAGOS_FIADOS_BOD_USUARIO1 FOREIGN KEY (USUARIO_ID) REFERENCES BOD_USUARIO (USUARIO_ID)
);
GO

CREATE TABLE BOD_VENTAS_FIADAS (
  VENTA_FIADA_ID INT IDENTITY(1,1) NOT NULL,
  VENTA_ID INT NOT NULL,
  CLIENTE_ID INT NOT NULL,
  PRIMARY KEY (VENTA_FIADA_ID),
  CONSTRAINT VENTA_ID_UNIQUE UNIQUE (VENTA_ID),
  CONSTRAINT fk_BOD_VENTAS_FIADAS_BOD_CLIENTE_AL_FIADO1 FOREIGN KEY (CLIENTE_ID) REFERENCES BOD_CLIENTE_AL_FIADO (CLIENTE_ID),
  CONSTRAINT fk_BOD_VENTAS_FIADAS_BOD_VENTAS1 FOREIGN KEY (VENTA_ID) REFERENCES BOD_VENTAS (VENTA_ID)
);
GO