USE TA_PROG3;
GO

DELETE FROM BOD_DETALLE_VENTA;
DELETE FROM BOD_DETALLE_DEVOLUCION;
DELETE FROM BOD_VENTAS_FIADAS;
DELETE FROM BOD_REGISTRO_PAGOS_FIADOS;
DELETE FROM BOD_HISTORIAL_OPERACIONES;
DELETE FROM BOD_VENTAS;
DELETE FROM BOD_DEVOLUCION;
DELETE FROM BOD_CLIENTE_AL_FIADO;
DELETE FROM BOD_PRODUCTO;
DELETE FROM BOD_RAZON_DEVOLUCION;
DELETE FROM BOD_CATEGORIA;
DELETE FROM BOD_USUARIO;
GO

DBCC CHECKIDENT ('BOD_CATEGORIA', RESEED, 0);
DBCC CHECKIDENT ('BOD_CLIENTE_AL_FIADO', RESEED, 0);
DBCC CHECKIDENT ('BOD_RAZON_DEVOLUCION', RESEED, 0);
DBCC CHECKIDENT ('BOD_PRODUCTO', RESEED, 0);
DBCC CHECKIDENT ('BOD_USUARIO', RESEED, 0);
DBCC CHECKIDENT ('BOD_VENTAS', RESEED, 0);
DBCC CHECKIDENT ('BOD_DEVOLUCION', RESEED, 0);
DBCC CHECKIDENT ('BOD_HISTORIAL_OPERACIONES', RESEED, 0);
DBCC CHECKIDENT ('BOD_REGISTRO_PAGOS_FIADOS', RESEED, 0);
DBCC CHECKIDENT ('BOD_VENTAS_FIADAS', RESEED, 0);
GO