//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBodBusiness.SoftWSClienteAlFiado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", ConfigurationName="SoftWSClienteAlFiado.ClienteAlFiado")]
    public interface ClienteAlFiado {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/modificarClienteAlFi" +
            "adoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/modificarClienteAlFi" +
            "adoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoResponse modificarClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/modificarClienteAlFi" +
            "adoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/modificarClienteAlFi" +
            "adoResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoResponse> modificarClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/listarTodosClientesA" +
            "lFiadoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/listarTodosClientesA" +
            "lFiadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoResponse listarTodosClientesAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/listarTodosClientesA" +
            "lFiadoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/listarTodosClientesA" +
            "lFiadoResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoResponse> listarTodosClientesAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/eliminarClienteAlFia" +
            "doRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/eliminarClienteAlFia" +
            "doResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoResponse eliminarClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/eliminarClienteAlFia" +
            "doRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/eliminarClienteAlFia" +
            "doResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoResponse> eliminarClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/insertarClienteAlFia" +
            "doRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/insertarClienteAlFia" +
            "doResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoResponse insertarClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/insertarClienteAlFia" +
            "doRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/insertarClienteAlFia" +
            "doResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoResponse> insertarClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/obtenerClienteAlFiad" +
            "oPorIdRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/obtenerClienteAlFiad" +
            "oPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdResponse obtenerClienteAlFiadoPorId(SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/obtenerClienteAlFiad" +
            "oPorIdRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/obtenerClienteAlFiad" +
            "oPorIdResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdResponse> obtenerClienteAlFiadoPorIdAsync(SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdRequest request);
        
        // CODEGEN: El parámetro 'clienteId' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/desbloquearClienteAl" +
            "FiadoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/desbloquearClienteAl" +
            "FiadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoResponse desbloquearClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/desbloquearClienteAl" +
            "FiadoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/desbloquearClienteAl" +
            "FiadoResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoResponse> desbloquearClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/listarTodosClientesA" +
            "lFiadoLikeRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/listarTodosClientesA" +
            "lFiadoLikeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeResponse listarTodosClientesAlFiadoLike(SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/listarTodosClientesA" +
            "lFiadoLikeRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/listarTodosClientesA" +
            "lFiadoLikeResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeResponse> listarTodosClientesAlFiadoLikeAsync(SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeRequest request);
        
        // CODEGEN: El parámetro 'clienteId' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/bloquearClienteAlFia" +
            "doPorMorosidadRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/bloquearClienteAlFia" +
            "doPorMorosidadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadResponse bloquearClienteAlFiadoPorMorosidad(SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/bloquearClienteAlFia" +
            "doPorMorosidadRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/ClienteAlFiado/bloquearClienteAlFia" +
            "doPorMorosidadResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadResponse> bloquearClienteAlFiadoPorMorosidadAsync(SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class clienteAlFiadoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string aliasField;
        
        private int clienteIdField;
        
        private bool clienteIdFieldSpecified;
        
        private string fechaDePagoField;
        
        private double montoDeudaField;
        
        private bool montoDeudaFieldSpecified;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int clienteId {
            get {
                return this.clienteIdField;
            }
            set {
                this.clienteIdField = value;
                this.RaisePropertyChanged("clienteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clienteIdSpecified {
            get {
                return this.clienteIdFieldSpecified;
            }
            set {
                this.clienteIdFieldSpecified = value;
                this.RaisePropertyChanged("clienteIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaDePago {
            get {
                return this.fechaDePagoField;
            }
            set {
                this.fechaDePagoField = value;
                this.RaisePropertyChanged("fechaDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double montoDeuda {
            get {
                return this.montoDeudaField;
            }
            set {
                this.montoDeudaField = value;
                this.RaisePropertyChanged("montoDeuda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoDeudaSpecified {
            get {
                return this.montoDeudaFieldSpecified;
            }
            set {
                this.montoDeudaFieldSpecified = value;
                this.RaisePropertyChanged("montoDeudaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarClienteAlFiado", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarClienteAlFiadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO clienteModificado;
        
        public modificarClienteAlFiadoRequest() {
        }
        
        public modificarClienteAlFiadoRequest(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO clienteModificado) {
            this.clienteModificado = clienteModificado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarClienteAlFiadoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarClienteAlFiadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarClienteAlFiadoResponse() {
        }
        
        public modificarClienteAlFiadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosClientesAlFiado", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosClientesAlFiadoRequest {
        
        public listarTodosClientesAlFiadoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosClientesAlFiadoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosClientesAlFiadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO[] @return;
        
        public listarTodosClientesAlFiadoResponse() {
        }
        
        public listarTodosClientesAlFiadoResponse(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarClienteAlFiado", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarClienteAlFiadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO clienteAeliminar;
        
        public eliminarClienteAlFiadoRequest() {
        }
        
        public eliminarClienteAlFiadoRequest(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO clienteAeliminar) {
            this.clienteAeliminar = clienteAeliminar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarClienteAlFiadoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarClienteAlFiadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarClienteAlFiadoResponse() {
        }
        
        public eliminarClienteAlFiadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarClienteAlFiado", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarClienteAlFiadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alias;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaDePago;
        
        public insertarClienteAlFiadoRequest() {
        }
        
        public insertarClienteAlFiadoRequest(string alias, string nombre, string telefono, string fechaDePago) {
            this.alias = alias;
            this.nombre = nombre;
            this.telefono = telefono;
            this.fechaDePago = fechaDePago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarClienteAlFiadoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarClienteAlFiadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarClienteAlFiadoResponse() {
        }
        
        public insertarClienteAlFiadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerClienteAlFiadoPorId", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClienteAlFiadoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int clienteId;
        
        public obtenerClienteAlFiadoPorIdRequest() {
        }
        
        public obtenerClienteAlFiadoPorIdRequest(int clienteId) {
            this.clienteId = clienteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerClienteAlFiadoPorIdResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClienteAlFiadoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO @return;
        
        public obtenerClienteAlFiadoPorIdResponse() {
        }
        
        public obtenerClienteAlFiadoPorIdResponse(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desbloquearClienteAlFiado", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class desbloquearClienteAlFiadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int clienteId;
        
        public desbloquearClienteAlFiadoRequest() {
        }
        
        public desbloquearClienteAlFiadoRequest(int clienteId) {
            this.clienteId = clienteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desbloquearClienteAlFiadoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class desbloquearClienteAlFiadoResponse {
        
        public desbloquearClienteAlFiadoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosClientesAlFiadoLike", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosClientesAlFiadoLikeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cadena;
        
        public listarTodosClientesAlFiadoLikeRequest() {
        }
        
        public listarTodosClientesAlFiadoLikeRequest(string cadena) {
            this.cadena = cadena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosClientesAlFiadoLikeResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosClientesAlFiadoLikeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO[] @return;
        
        public listarTodosClientesAlFiadoLikeResponse() {
        }
        
        public listarTodosClientesAlFiadoLikeResponse(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bloquearClienteAlFiadoPorMorosidad", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class bloquearClienteAlFiadoPorMorosidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int clienteId;
        
        public bloquearClienteAlFiadoPorMorosidadRequest() {
        }
        
        public bloquearClienteAlFiadoPorMorosidadRequest(int clienteId) {
            this.clienteId = clienteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bloquearClienteAlFiadoPorMorosidadResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class bloquearClienteAlFiadoPorMorosidadResponse {
        
        public bloquearClienteAlFiadoPorMorosidadResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteAlFiadoChannel : SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteAlFiadoClient : System.ServiceModel.ClientBase<SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado>, SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado {
        
        public ClienteAlFiadoClient() {
        }
        
        public ClienteAlFiadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteAlFiadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteAlFiadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteAlFiadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoResponse SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.modificarClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoRequest request) {
            return base.Channel.modificarClienteAlFiado(request);
        }
        
        public int modificarClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO clienteModificado) {
            SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoRequest();
            inValue.clienteModificado = clienteModificado;
            SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoResponse retVal = ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).modificarClienteAlFiado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoResponse> SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.modificarClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoRequest request) {
            return base.Channel.modificarClienteAlFiadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoResponse> modificarClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO clienteModificado) {
            SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.modificarClienteAlFiadoRequest();
            inValue.clienteModificado = clienteModificado;
            return ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).modificarClienteAlFiadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoResponse SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.listarTodosClientesAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoRequest request) {
            return base.Channel.listarTodosClientesAlFiado(request);
        }
        
        public SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO[] listarTodosClientesAlFiado() {
            SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoRequest();
            SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoResponse retVal = ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).listarTodosClientesAlFiado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoResponse> SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.listarTodosClientesAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoRequest request) {
            return base.Channel.listarTodosClientesAlFiadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoResponse> listarTodosClientesAlFiadoAsync() {
            SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoRequest();
            return ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).listarTodosClientesAlFiadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoResponse SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.eliminarClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoRequest request) {
            return base.Channel.eliminarClienteAlFiado(request);
        }
        
        public int eliminarClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO clienteAeliminar) {
            SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoRequest();
            inValue.clienteAeliminar = clienteAeliminar;
            SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoResponse retVal = ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).eliminarClienteAlFiado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoResponse> SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.eliminarClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoRequest request) {
            return base.Channel.eliminarClienteAlFiadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoResponse> eliminarClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO clienteAeliminar) {
            SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.eliminarClienteAlFiadoRequest();
            inValue.clienteAeliminar = clienteAeliminar;
            return ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).eliminarClienteAlFiadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoResponse SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.insertarClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoRequest request) {
            return base.Channel.insertarClienteAlFiado(request);
        }
        
        public int insertarClienteAlFiado(string alias, string nombre, string telefono, string fechaDePago) {
            SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoRequest();
            inValue.alias = alias;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            inValue.fechaDePago = fechaDePago;
            SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoResponse retVal = ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).insertarClienteAlFiado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoResponse> SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.insertarClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoRequest request) {
            return base.Channel.insertarClienteAlFiadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoResponse> insertarClienteAlFiadoAsync(string alias, string nombre, string telefono, string fechaDePago) {
            SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.insertarClienteAlFiadoRequest();
            inValue.alias = alias;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            inValue.fechaDePago = fechaDePago;
            return ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).insertarClienteAlFiadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdResponse SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.obtenerClienteAlFiadoPorId(SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdRequest request) {
            return base.Channel.obtenerClienteAlFiadoPorId(request);
        }
        
        public SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO obtenerClienteAlFiadoPorId(int clienteId) {
            SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdRequest();
            inValue.clienteId = clienteId;
            SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdResponse retVal = ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).obtenerClienteAlFiadoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdResponse> SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.obtenerClienteAlFiadoPorIdAsync(SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdRequest request) {
            return base.Channel.obtenerClienteAlFiadoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdResponse> obtenerClienteAlFiadoPorIdAsync(int clienteId) {
            SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.obtenerClienteAlFiadoPorIdRequest();
            inValue.clienteId = clienteId;
            return ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).obtenerClienteAlFiadoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoResponse SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.desbloquearClienteAlFiado(SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoRequest request) {
            return base.Channel.desbloquearClienteAlFiado(request);
        }
        
        public void desbloquearClienteAlFiado(int clienteId) {
            SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoRequest();
            inValue.clienteId = clienteId;
            SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoResponse retVal = ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).desbloquearClienteAlFiado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoResponse> SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.desbloquearClienteAlFiadoAsync(SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoRequest request) {
            return base.Channel.desbloquearClienteAlFiadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoResponse> desbloquearClienteAlFiadoAsync(int clienteId) {
            SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.desbloquearClienteAlFiadoRequest();
            inValue.clienteId = clienteId;
            return ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).desbloquearClienteAlFiadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeResponse SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.listarTodosClientesAlFiadoLike(SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeRequest request) {
            return base.Channel.listarTodosClientesAlFiadoLike(request);
        }
        
        public SoftBodBusiness.SoftWSClienteAlFiado.clienteAlFiadoDTO[] listarTodosClientesAlFiadoLike(string cadena) {
            SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeRequest();
            inValue.cadena = cadena;
            SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeResponse retVal = ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).listarTodosClientesAlFiadoLike(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeResponse> SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.listarTodosClientesAlFiadoLikeAsync(SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeRequest request) {
            return base.Channel.listarTodosClientesAlFiadoLikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeResponse> listarTodosClientesAlFiadoLikeAsync(string cadena) {
            SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.listarTodosClientesAlFiadoLikeRequest();
            inValue.cadena = cadena;
            return ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).listarTodosClientesAlFiadoLikeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadResponse SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.bloquearClienteAlFiadoPorMorosidad(SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadRequest request) {
            return base.Channel.bloquearClienteAlFiadoPorMorosidad(request);
        }
        
        public void bloquearClienteAlFiadoPorMorosidad(int clienteId) {
            SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadRequest();
            inValue.clienteId = clienteId;
            SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadResponse retVal = ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).bloquearClienteAlFiadoPorMorosidad(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadResponse> SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado.bloquearClienteAlFiadoPorMorosidadAsync(SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadRequest request) {
            return base.Channel.bloquearClienteAlFiadoPorMorosidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadResponse> bloquearClienteAlFiadoPorMorosidadAsync(int clienteId) {
            SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadRequest inValue = new SoftBodBusiness.SoftWSClienteAlFiado.bloquearClienteAlFiadoPorMorosidadRequest();
            inValue.clienteId = clienteId;
            return ((SoftBodBusiness.SoftWSClienteAlFiado.ClienteAlFiado)(this)).bloquearClienteAlFiadoPorMorosidadAsync(inValue);
        }
    }
}
