CREATE DATABASE IF NOT EXISTS `TA_PROG3`;
USE `TA_PROG3`;

DROP TABLE IF EXISTS `BOD_DETALLE_VENTA`;
DROP TABLE IF EXISTS `BOD_DETALLE_DEVOLUCION`;
DROP TABLE IF EXISTS `BOD_VENTAS_FIADAS`;
DROP TABLE IF EXISTS `BOD_REGISTRO_PAGOS_FIADOS`;
DROP TABLE IF EXISTS `BOD_HISTORIAL_OPERACIONES`;
DROP TABLE IF EXISTS `BOD_VENTAS`;
DROP TABLE IF EXISTS `BOD_DEVOLUCION`;
DROP TABLE IF EXISTS `BOD_CLIENTE_AL_FIADO`;
DROP TABLE IF EXISTS `BOD_PRODUCTO`;
DROP TABLE IF EXISTS `BOD_RAZON_DEVOLUCION`;
DROP TABLE IF EXISTS `BOD_CATEGORIA`;
DROP TABLE IF EXISTS `BOD_USUARIO`;

CREATE TABLE `BOD_CATEGORIA` (
  `CATEGORIA_ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(60) NOT NULL,
  PRIMARY KEY (`CATEGORIA_ID`),
  UNIQUE KEY `DESCRIPCION_UNIQUE` (`DESCRIPCION`)
);

CREATE TABLE `BOD_CLIENTE_AL_FIADO` (
  `CLIENTE_ID` int NOT NULL AUTO_INCREMENT,
  `ALIAS` varchar(40) NOT NULL,
  `NOMBRE` varchar(60) NOT NULL,
  `TELEFONO` varchar(9) NOT NULL,
  `FECHA_DE_PAGO` date NOT NULL,
  `ACTIVO` tinyint NOT NULL,
  `MONTO_DEUDA` decimal(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`CLIENTE_ID`),
  UNIQUE KEY `ALIAS_UNIQUE` (`ALIAS`)
);

CREATE TABLE `BOD_RAZON_DEVOLUCION` (
  `RAZON_DEVOLUCION_ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(60) NOT NULL,
  PRIMARY KEY (`RAZON_DEVOLUCION_ID`),
  UNIQUE KEY `DESCRIPCION_UNIQUE` (`DESCRIPCION`)
);

CREATE TABLE `BOD_PRODUCTO` (
  `PRODUCTO_ID` int NOT NULL AUTO_INCREMENT,
  `CATEGORIA_ID` int NOT NULL,
  `NOMBRE` varchar(45) NOT NULL,
  `PRECIO_UNITARIO` decimal(10,2) NOT NULL,
  `UNIDAD_MEDIDA` enum('KILOGRAMO','LITRO','UNIDAD') NOT NULL,
  `STOCK` int NOT NULL,
  `STOCK_MINIMO` int NOT NULL,
  `ACTIVO` tinyint NOT NULL,
  PRIMARY KEY (`PRODUCTO_ID`),
  KEY `fk_BOD_PRODUCTO_BOD_CATEGORIA1_idx` (`CATEGORIA_ID`),
  CONSTRAINT `fk_BOD_PRODUCTO_BOD_CATEGORIA1` FOREIGN KEY (`CATEGORIA_ID`) REFERENCES `BOD_CATEGORIA` (`CATEGORIA_ID`)
);

CREATE TABLE `BOD_USUARIO` (
  `USUARIO_ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO` varchar(30) NOT NULL,
  `TIPO_USUARIOS` enum('ADMINISTRADOR','OPERARIO') NOT NULL,
  `CORREO` varchar(45) NOT NULL,
  `CONTRASENHA` varchar(30) NOT NULL,
  `NOMBRE_COMPLETO` varchar(100) NOT NULL,
  `TELEFONO_USUARIO` varchar(9) NOT NULL,
  `ACTIVO_USUARIO` tinyint NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  UNIQUE KEY `USUARIO_OPERARIO_UNIQUE` (`USUARIO`)
);

CREATE TABLE `BOD_VENTAS` (
  `VENTA_ID` int NOT NULL AUTO_INCREMENT,
  `TOTAL` decimal(10,2) NOT NULL,
  `METODO_PAGO` enum('EFECTIVO','TRANSFERENCIA','FIADO') NOT NULL,
  `FECHA` datetime NOT NULL,
  `USUARIO_ID` int NOT NULL,
  PRIMARY KEY (`VENTA_ID`),
  KEY `fk_BOD_VENTAS_BOD_USUARIO1_idx` (`USUARIO_ID`),
  CONSTRAINT `fk_BOD_VENTAS_BOD_USUARIO1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `BOD_USUARIO` (`USUARIO_ID`)
);

CREATE TABLE `BOD_DEVOLUCION` (
  `DEVOLUCION_ID` int NOT NULL AUTO_INCREMENT,
  `TOTAL` decimal(10,2) NOT NULL,
  `FECHA` datetime NOT NULL,
  `USUARIO_ID` int NOT NULL,
  PRIMARY KEY (`DEVOLUCION_ID`),
  KEY `fk_BOD_DEVOLUCION_BOD_USUARIO1_idx` (`USUARIO_ID`),
  CONSTRAINT `fk_BOD_DEVOLUCION_BOD_USUARIO1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `BOD_USUARIO` (`USUARIO_ID`)
);

CREATE TABLE `BOD_DETALLE_DEVOLUCION` (
  `DEVOLUCION_ID` int NOT NULL,
  `PRODUCTO_ID` int NOT NULL,
  `SUBTOTAL` decimal(10,2) NOT NULL,
  `CANTIDAD` int NOT NULL,
  `RAZON_DEVOLUCION_ID` int NOT NULL,
  PRIMARY KEY (`DEVOLUCION_ID`,`PRODUCTO_ID`),
  KEY `fk_BOD_DETALLE_FIADO_BOD_DEVOLUCION1_idx` (`DEVOLUCION_ID`),
  KEY `fk_BOD_DETALLE_FIADO_BOD_PRODUCTO1_idx` (`PRODUCTO_ID`),
  KEY `fk_BOD_DETALLE_DEVOLUCION_BOD_RAZON_DEVOLUCION1_idx` (`RAZON_DEVOLUCION_ID`),
  CONSTRAINT `fk_BOD_DETALLE_DEVOLUCION_BOD_RAZON_DEVOLUCION1` FOREIGN KEY (`RAZON_DEVOLUCION_ID`) REFERENCES `BOD_RAZON_DEVOLUCION` (`RAZON_DEVOLUCION_ID`),
  CONSTRAINT `fk_BOD_DETALLE_FIADO_BOD_DEVOLUCION1` FOREIGN KEY (`DEVOLUCION_ID`) REFERENCES `BOD_DEVOLUCION` (`DEVOLUCION_ID`),
  CONSTRAINT `fk_BOD_DETALLE_FIADO_BOD_PRODUCTO1` FOREIGN KEY (`PRODUCTO_ID`) REFERENCES `BOD_PRODUCTO` (`PRODUCTO_ID`)
);

CREATE TABLE `BOD_DETALLE_VENTA` (
  `VENTA_ID` int NOT NULL,
  `PRODUCTO_ID` int NOT NULL,
  `SUBTOTAL` decimal(10,2) NOT NULL,
  `CANTIDAD` int NOT NULL,
  PRIMARY KEY (`VENTA_ID`,`PRODUCTO_ID`),
  KEY `fk_BOD_DETALLE_VENTA_BOD_VENTAS1_idx` (`VENTA_ID`),
  KEY `fk_BOD_DETALLE_VENTA_BOD_PRODUCTO1_idx` (`PRODUCTO_ID`),
  CONSTRAINT `fk_BOD_DETALLE_VENTA_BOD_PRODUCTO1` FOREIGN KEY (`PRODUCTO_ID`) REFERENCES `BOD_PRODUCTO` (`PRODUCTO_ID`),
  CONSTRAINT `fk_BOD_DETALLE_VENTA_BOD_VENTAS1` FOREIGN KEY (`VENTA_ID`) REFERENCES `BOD_VENTAS` (`VENTA_ID`)
);

CREATE TABLE `BOD_HISTORIAL_OPERACIONES` (
  `OPERACION_ID` int NOT NULL AUTO_INCREMENT,
  `TABLA_AFECTADA` varchar(60) NOT NULL,
  `OPERACION` enum('INSERCION','MODIFICACION','ELIMINACION','CONSULTAR') NOT NULL,
  `FECHA_HORA` datetime NOT NULL,
  `USUARIO_ID` int NOT NULL,
  PRIMARY KEY (`OPERACION_ID`),
  UNIQUE KEY `OPERACION_ID_UNIQUE` (`OPERACION_ID`),
  KEY `fk_BOD_HISTORIAL_OPERACIONES_BOD_USUARIO1_idx` (`USUARIO_ID`),
  CONSTRAINT `fk_BOD_HISTORIAL_OPERACIONES_BOD_USUARIO1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `BOD_USUARIO` (`USUARIO_ID`)
);

CREATE TABLE `BOD_REGISTRO_PAGOS_FIADOS` (
  `PAGO_ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` int NOT NULL,
  `CLIENTE_ID` int NOT NULL,
  `FECHA` datetime NOT NULL,
  `METODO_PAGO` enum('EFECTIVO','TRANSFERENCIA') NOT NULL,
  `MONTO` decimal(10,2) NOT NULL,
  PRIMARY KEY (`PAGO_ID`),
  KEY `fk_BOD_REGISTRO_PAGOS_FIADOS_BOD_USUARIO1_idx` (`USUARIO_ID`),
  KEY `fk_BOD_REGISTRO_PAGOS_FIADOS_BOD_CLIENTE_AL_FIADO1_idx` (`CLIENTE_ID`),
  CONSTRAINT `fk_BOD_REGISTRO_PAGOS_FIADOS_BOD_CLIENTE_AL_FIADO1` FOREIGN KEY (`CLIENTE_ID`) REFERENCES `BOD_CLIENTE_AL_FIADO` (`CLIENTE_ID`),
  CONSTRAINT `fk_BOD_REGISTRO_PAGOS_FIADOS_BOD_USUARIO1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `BOD_USUARIO` (`USUARIO_ID`)
);

CREATE TABLE `BOD_VENTAS_FIADAS` (
  `VENTA_FIADA_ID` int NOT NULL AUTO_INCREMENT,
  `VENTA_ID` int NOT NULL,
  `CLIENTE_ID` int NOT NULL,
  PRIMARY KEY (`VENTA_FIADA_ID`),
  UNIQUE KEY `VENTA_ID_UNIQUE` (`VENTA_ID`),
  KEY `fk_BOD_VENTAS_FIADAS_BOD_VENTAS1_idx` (`VENTA_ID`),
  KEY `fk_BOD_VENTAS_FIADAS_BOD_CLIENTE_AL_FIADO1_idx` (`CLIENTE_ID`),
  CONSTRAINT `fk_BOD_VENTAS_FIADAS_BOD_CLIENTE_AL_FIADO1` FOREIGN KEY (`CLIENTE_ID`) REFERENCES `BOD_CLIENTE_AL_FIADO` (`CLIENTE_ID`),
  CONSTRAINT `fk_BOD_VENTAS_FIADAS_BOD_VENTAS1` FOREIGN KEY (`VENTA_ID`) REFERENCES `BOD_VENTAS` (`VENTA_ID`)
);