USE `TA_PROG3`;

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM `BOD_DETALLE_VENTA`;
DELETE FROM `BOD_DETALLE_DEVOLUCION`;
DELETE FROM `BOD_VENTAS_FIADAS`;
DELETE FROM `BOD_REGISTRO_PAGOS_FIADOS`;
DELETE FROM `BOD_HISTORIAL_OPERACIONES`;
DELETE FROM `BOD_VENTAS`;
DELETE FROM `BOD_DEVOLUCION`;
DELETE FROM `BOD_CLIENTE_AL_FIADO`;
DELETE FROM `BOD_PRODUCTO`;
DELETE FROM `BOD_RAZON_DEVOLUCION`;
DELETE FROM `BOD_CATEGORIA`;
DELETE FROM `BOD_USUARIO`;

ALTER TABLE `BOD_CATEGORIA` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_CLIENTE_AL_FIADO` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_RAZON_DEVOLUCION` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_PRODUCTO` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_USUARIO` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_VENTAS` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_DEVOLUCION` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_HISTORIAL_OPERACIONES` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_REGISTRO_PAGOS_FIADOS` AUTO_INCREMENT = 1;
ALTER TABLE `BOD_VENTAS_FIADAS` AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;