//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBodBusiness.SoftWSDetalleVenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", ConfigurationName="SoftWSDetalleVenta.DetalleVenta")]
    public interface DetalleVenta {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarDetallesVentaPor" +
            "ProductoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarDetallesVentaPor" +
            "ProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoResponse listarDetallesVentaPorProducto(SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarDetallesVentaPor" +
            "ProductoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarDetallesVentaPor" +
            "ProductoResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoResponse> listarDetallesVentaPorProductoAsync(SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarDetallesVentaPor" +
            "VentaRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarDetallesVentaPor" +
            "VentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaResponse listarDetallesVentaPorVenta(SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarDetallesVentaPor" +
            "VentaRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarDetallesVentaPor" +
            "VentaResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaResponse> listarDetallesVentaPorVentaAsync(SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/obtenerDetalleVentaPor" +
            "IdRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/obtenerDetalleVentaPor" +
            "IdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdResponse obtenerDetalleVentaPorId(SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/obtenerDetalleVentaPor" +
            "IdRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/obtenerDetalleVentaPor" +
            "IdResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdResponse> obtenerDetalleVentaPorIdAsync(SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarTodosDetallesVen" +
            "taRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarTodosDetallesVen" +
            "taResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaResponse listarTodosDetallesVenta(SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarTodosDetallesVen" +
            "taRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/listarTodosDetallesVen" +
            "taResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaResponse> listarTodosDetallesVentaAsync(SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/insertarDetalleVentaRe" +
            "quest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/insertarDetalleVentaRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaResponse insertarDetalleVenta(SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/insertarDetalleVentaRe" +
            "quest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/DetalleVenta/insertarDetalleVentaRe" +
            "sponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaResponse> insertarDetalleVentaAsync(SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class detalleVentaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private productoDTO productoField;
        
        private double subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private ventaDTO ventaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
                this.RaisePropertyChanged("subtotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ventaDTO venta {
            get {
                return this.ventaField;
            }
            set {
                this.ventaField = value;
                this.RaisePropertyChanged("venta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private categoriaDTO categoriaField;
        
        private string nombreField;
        
        private double precioUnitarioField;
        
        private bool precioUnitarioFieldSpecified;
        
        private int productoIdField;
        
        private bool productoIdFieldSpecified;
        
        private int stockField;
        
        private bool stockFieldSpecified;
        
        private int stockMinimoField;
        
        private bool stockMinimoFieldSpecified;
        
        private unidadMedida unidadMedidaField;
        
        private bool unidadMedidaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categoriaDTO categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioUnitarioSpecified {
            get {
                return this.precioUnitarioFieldSpecified;
            }
            set {
                this.precioUnitarioFieldSpecified = value;
                this.RaisePropertyChanged("precioUnitarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int productoId {
            get {
                return this.productoIdField;
            }
            set {
                this.productoIdField = value;
                this.RaisePropertyChanged("productoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productoIdSpecified {
            get {
                return this.productoIdFieldSpecified;
            }
            set {
                this.productoIdFieldSpecified = value;
                this.RaisePropertyChanged("productoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockSpecified {
            get {
                return this.stockFieldSpecified;
            }
            set {
                this.stockFieldSpecified = value;
                this.RaisePropertyChanged("stockSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockMinimoSpecified {
            get {
                return this.stockMinimoFieldSpecified;
            }
            set {
                this.stockMinimoFieldSpecified = value;
                this.RaisePropertyChanged("stockMinimoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public unidadMedida unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unidadMedidaSpecified {
            get {
                return this.unidadMedidaFieldSpecified;
            }
            set {
                this.unidadMedidaFieldSpecified = value;
                this.RaisePropertyChanged("unidadMedidaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class categoriaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int categoriaIdField;
        
        private bool categoriaIdFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int categoriaId {
            get {
                return this.categoriaIdField;
            }
            set {
                this.categoriaIdField = value;
                this.RaisePropertyChanged("categoriaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaIdSpecified {
            get {
                return this.categoriaIdFieldSpecified;
            }
            set {
                this.categoriaIdFieldSpecified = value;
                this.RaisePropertyChanged("categoriaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string contrasenhaField;
        
        private string correoField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private tipoUsuario tipoUsuariosField;
        
        private bool tipoUsuariosFieldSpecified;
        
        private string usuarioField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoUsuario tipoUsuarios {
            get {
                return this.tipoUsuariosField;
            }
            set {
                this.tipoUsuariosField = value;
                this.RaisePropertyChanged("tipoUsuarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuariosSpecified {
            get {
                return this.tipoUsuariosFieldSpecified;
            }
            set {
                this.tipoUsuariosFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuariosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        OPERARIO,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class ventaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private tipoDePago metodoPagoField;
        
        private bool metodoPagoFieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        private int ventaIdField;
        
        private bool ventaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoDePago metodoPago {
            get {
                return this.metodoPagoField;
            }
            set {
                this.metodoPagoField = value;
                this.RaisePropertyChanged("metodoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metodoPagoSpecified {
            get {
                return this.metodoPagoFieldSpecified;
            }
            set {
                this.metodoPagoFieldSpecified = value;
                this.RaisePropertyChanged("metodoPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int ventaId {
            get {
                return this.ventaIdField;
            }
            set {
                this.ventaIdField = value;
                this.RaisePropertyChanged("ventaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ventaIdSpecified {
            get {
                return this.ventaIdFieldSpecified;
            }
            set {
                this.ventaIdFieldSpecified = value;
                this.RaisePropertyChanged("ventaIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public enum tipoDePago {
        
        /// <remarks/>
        EFECTIVO,
        
        /// <remarks/>
        TRANSFERENCIA,
        
        /// <remarks/>
        FIADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public enum unidadMedida {
        
        /// <remarks/>
        KILOGRAMO,
        
        /// <remarks/>
        LITRO,
        
        /// <remarks/>
        UNIDAD,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDetallesVentaPorProducto", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDetallesVentaPorProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        public listarDetallesVentaPorProductoRequest() {
        }
        
        public listarDetallesVentaPorProductoRequest(int productoId) {
            this.productoId = productoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDetallesVentaPorProductoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDetallesVentaPorProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] @return;
        
        public listarDetallesVentaPorProductoResponse() {
        }
        
        public listarDetallesVentaPorProductoResponse(SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDetallesVentaPorVenta", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDetallesVentaPorVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ventaId;
        
        public listarDetallesVentaPorVentaRequest() {
        }
        
        public listarDetallesVentaPorVentaRequest(int ventaId) {
            this.ventaId = ventaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDetallesVentaPorVentaResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDetallesVentaPorVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] @return;
        
        public listarDetallesVentaPorVentaResponse() {
        }
        
        public listarDetallesVentaPorVentaResponse(SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDetalleVentaPorId", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDetalleVentaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ventaId;
        
        public obtenerDetalleVentaPorIdRequest() {
        }
        
        public obtenerDetalleVentaPorIdRequest(int productoId, int ventaId) {
            this.productoId = productoId;
            this.ventaId = ventaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDetalleVentaPorIdResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDetalleVentaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO @return;
        
        public obtenerDetalleVentaPorIdResponse() {
        }
        
        public obtenerDetalleVentaPorIdResponse(SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDetallesVenta", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDetallesVentaRequest {
        
        public listarTodosDetallesVentaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDetallesVentaResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDetallesVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] @return;
        
        public listarTodosDetallesVentaResponse() {
        }
        
        public listarTodosDetallesVentaResponse(SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDetalleVenta", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDetalleVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO detalleVenta;
        
        public insertarDetalleVentaRequest() {
        }
        
        public insertarDetalleVentaRequest(SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO detalleVenta) {
            this.detalleVenta = detalleVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDetalleVentaResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDetalleVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarDetalleVentaResponse() {
        }
        
        public insertarDetalleVentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DetalleVentaChannel : SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetalleVentaClient : System.ServiceModel.ClientBase<SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta>, SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta {
        
        public DetalleVentaClient() {
        }
        
        public DetalleVentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DetalleVentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetalleVentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetalleVentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoResponse SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.listarDetallesVentaPorProducto(SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoRequest request) {
            return base.Channel.listarDetallesVentaPorProducto(request);
        }
        
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] listarDetallesVentaPorProducto(int productoId) {
            SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoRequest();
            inValue.productoId = productoId;
            SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoResponse retVal = ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).listarDetallesVentaPorProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoResponse> SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.listarDetallesVentaPorProductoAsync(SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoRequest request) {
            return base.Channel.listarDetallesVentaPorProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoResponse> listarDetallesVentaPorProductoAsync(int productoId) {
            SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorProductoRequest();
            inValue.productoId = productoId;
            return ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).listarDetallesVentaPorProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaResponse SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.listarDetallesVentaPorVenta(SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaRequest request) {
            return base.Channel.listarDetallesVentaPorVenta(request);
        }
        
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] listarDetallesVentaPorVenta(int ventaId) {
            SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaRequest();
            inValue.ventaId = ventaId;
            SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaResponse retVal = ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).listarDetallesVentaPorVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaResponse> SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.listarDetallesVentaPorVentaAsync(SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaRequest request) {
            return base.Channel.listarDetallesVentaPorVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaResponse> listarDetallesVentaPorVentaAsync(int ventaId) {
            SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.listarDetallesVentaPorVentaRequest();
            inValue.ventaId = ventaId;
            return ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).listarDetallesVentaPorVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdResponse SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.obtenerDetalleVentaPorId(SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdRequest request) {
            return base.Channel.obtenerDetalleVentaPorId(request);
        }
        
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO obtenerDetalleVentaPorId(int productoId, int ventaId) {
            SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdRequest();
            inValue.productoId = productoId;
            inValue.ventaId = ventaId;
            SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdResponse retVal = ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).obtenerDetalleVentaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdResponse> SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.obtenerDetalleVentaPorIdAsync(SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdRequest request) {
            return base.Channel.obtenerDetalleVentaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdResponse> obtenerDetalleVentaPorIdAsync(int productoId, int ventaId) {
            SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.obtenerDetalleVentaPorIdRequest();
            inValue.productoId = productoId;
            inValue.ventaId = ventaId;
            return ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).obtenerDetalleVentaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaResponse SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.listarTodosDetallesVenta(SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaRequest request) {
            return base.Channel.listarTodosDetallesVenta(request);
        }
        
        public SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO[] listarTodosDetallesVenta() {
            SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaRequest();
            SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaResponse retVal = ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).listarTodosDetallesVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaResponse> SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.listarTodosDetallesVentaAsync(SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaRequest request) {
            return base.Channel.listarTodosDetallesVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaResponse> listarTodosDetallesVentaAsync() {
            SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.listarTodosDetallesVentaRequest();
            return ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).listarTodosDetallesVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaResponse SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.insertarDetalleVenta(SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaRequest request) {
            return base.Channel.insertarDetalleVenta(request);
        }
        
        public int insertarDetalleVenta(SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO detalleVenta) {
            SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaRequest();
            inValue.detalleVenta = detalleVenta;
            SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaResponse retVal = ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).insertarDetalleVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaResponse> SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta.insertarDetalleVentaAsync(SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaRequest request) {
            return base.Channel.insertarDetalleVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaResponse> insertarDetalleVentaAsync(SoftBodBusiness.SoftWSDetalleVenta.detalleVentaDTO detalleVenta) {
            SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaRequest inValue = new SoftBodBusiness.SoftWSDetalleVenta.insertarDetalleVentaRequest();
            inValue.detalleVenta = detalleVenta;
            return ((SoftBodBusiness.SoftWSDetalleVenta.DetalleVenta)(this)).insertarDetalleVentaAsync(inValue);
        }
    }
}
