//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBodBusiness.SoftWSProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", ConfigurationName="SoftWSProducto.Producto")]
    public interface Producto {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/eliminarProductoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/eliminarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSProducto.eliminarProductoResponse eliminarProducto(SoftBodBusiness.SoftWSProducto.eliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/eliminarProductoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/eliminarProductoResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.eliminarProductoResponse> eliminarProductoAsync(SoftBodBusiness.SoftWSProducto.eliminarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/modificarProductoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/modificarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSProducto.modificarProductoResponse modificarProducto(SoftBodBusiness.SoftWSProducto.modificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/modificarProductoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/modificarProductoResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.modificarProductoResponse> modificarProductoAsync(SoftBodBusiness.SoftWSProducto.modificarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/insertarProductoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/insertarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSProducto.insertarProductoResponse insertarProducto(SoftBodBusiness.SoftWSProducto.insertarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/insertarProductoRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/insertarProductoResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.insertarProductoResponse> insertarProductoAsync(SoftBodBusiness.SoftWSProducto.insertarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/listarTodosProductosReques" +
            "t", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/listarTodosProductosRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSProducto.listarTodosProductosResponse listarTodosProductos(SoftBodBusiness.SoftWSProducto.listarTodosProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/listarTodosProductosReques" +
            "t", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/listarTodosProductosRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.listarTodosProductosResponse> listarTodosProductosAsync(SoftBodBusiness.SoftWSProducto.listarTodosProductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/obtenerProductoPorIdReques" +
            "t", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/obtenerProductoPorIdRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdResponse obtenerProductoPorId(SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/obtenerProductoPorIdReques" +
            "t", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/obtenerProductoPorIdRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdResponse> obtenerProductoPorIdAsync(SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/listarTodosConFiltroProduc" +
            "tosRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/listarTodosConFiltroProduc" +
            "tosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosResponse listarTodosConFiltroProductos(SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softbodws.services.softbod.pucp.edu.pe/Producto/listarTodosConFiltroProduc" +
            "tosRequest", ReplyAction="http://softbodws.services.softbod.pucp.edu.pe/Producto/listarTodosConFiltroProduc" +
            "tosResponse")]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosResponse> listarTodosConFiltroProductosAsync(SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProducto", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        public eliminarProductoRequest() {
        }
        
        public eliminarProductoRequest(int productoId) {
            this.productoId = productoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarProductoResponse() {
        }
        
        public eliminarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private categoriaDTO categoriaField;
        
        private string nombreField;
        
        private double precioUnitarioField;
        
        private bool precioUnitarioFieldSpecified;
        
        private int productoIdField;
        
        private bool productoIdFieldSpecified;
        
        private int stockField;
        
        private bool stockFieldSpecified;
        
        private int stockMinimoField;
        
        private bool stockMinimoFieldSpecified;
        
        private unidadMedida unidadMedidaField;
        
        private bool unidadMedidaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categoriaDTO categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioUnitarioSpecified {
            get {
                return this.precioUnitarioFieldSpecified;
            }
            set {
                this.precioUnitarioFieldSpecified = value;
                this.RaisePropertyChanged("precioUnitarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int productoId {
            get {
                return this.productoIdField;
            }
            set {
                this.productoIdField = value;
                this.RaisePropertyChanged("productoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productoIdSpecified {
            get {
                return this.productoIdFieldSpecified;
            }
            set {
                this.productoIdFieldSpecified = value;
                this.RaisePropertyChanged("productoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockSpecified {
            get {
                return this.stockFieldSpecified;
            }
            set {
                this.stockFieldSpecified = value;
                this.RaisePropertyChanged("stockSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockMinimoSpecified {
            get {
                return this.stockMinimoFieldSpecified;
            }
            set {
                this.stockMinimoFieldSpecified = value;
                this.RaisePropertyChanged("stockMinimoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public unidadMedida unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unidadMedidaSpecified {
            get {
                return this.unidadMedidaFieldSpecified;
            }
            set {
                this.unidadMedidaFieldSpecified = value;
                this.RaisePropertyChanged("unidadMedidaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public partial class categoriaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int categoriaIdField;
        
        private bool categoriaIdFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int categoriaId {
            get {
                return this.categoriaIdField;
            }
            set {
                this.categoriaIdField = value;
                this.RaisePropertyChanged("categoriaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaIdSpecified {
            get {
                return this.categoriaIdFieldSpecified;
            }
            set {
                this.categoriaIdFieldSpecified = value;
                this.RaisePropertyChanged("categoriaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/")]
    public enum unidadMedida {
        
        /// <remarks/>
        KILOGRAMO,
        
        /// <remarks/>
        LITRO,
        
        /// <remarks/>
        UNIDAD,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProducto", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSProducto.productoDTO producto;
        
        public modificarProductoRequest() {
        }
        
        public modificarProductoRequest(SoftBodBusiness.SoftWSProducto.productoDTO producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProductoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarProductoResponse() {
        }
        
        public modificarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProducto", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSProducto.categoriaDTO categoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioUnitario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unidadMedida;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stockMinimo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public insertarProductoRequest() {
        }
        
        public insertarProductoRequest(SoftBodBusiness.SoftWSProducto.categoriaDTO categoria, string nombre, double precioUnitario, string unidadMedida, int stock, int stockMinimo, bool activo) {
            this.categoria = categoria;
            this.nombre = nombre;
            this.precioUnitario = precioUnitario;
            this.unidadMedida = unidadMedida;
            this.stock = stock;
            this.stockMinimo = stockMinimo;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarProductoResponse() {
        }
        
        public insertarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosProductos", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosProductosRequest {
        
        public listarTodosProductosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosProductosResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSProducto.productoDTO[] @return;
        
        public listarTodosProductosResponse() {
        }
        
        public listarTodosProductosResponse(SoftBodBusiness.SoftWSProducto.productoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProductoPorId", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerProductoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        public obtenerProductoPorIdRequest() {
        }
        
        public obtenerProductoPorIdRequest(int productoId) {
            this.productoId = productoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProductoPorIdResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerProductoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSProducto.productoDTO @return;
        
        public obtenerProductoPorIdResponse() {
        }
        
        public obtenerProductoPorIdResponse(SoftBodBusiness.SoftWSProducto.productoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosConFiltroProductos", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosConFiltroProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string categoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreProducto;
        
        public listarTodosConFiltroProductosRequest() {
        }
        
        public listarTodosConFiltroProductosRequest(bool activo, string categoria, string nombreProducto) {
            this.activo = activo;
            this.categoria = categoria;
            this.nombreProducto = nombreProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosConFiltroProductosResponse", WrapperNamespace="http://softbodws.services.softbod.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosConFiltroProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softbodws.services.softbod.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBodBusiness.SoftWSProducto.productoDTO[] @return;
        
        public listarTodosConFiltroProductosResponse() {
        }
        
        public listarTodosConFiltroProductosResponse(SoftBodBusiness.SoftWSProducto.productoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoChannel : SoftBodBusiness.SoftWSProducto.Producto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoClient : System.ServiceModel.ClientBase<SoftBodBusiness.SoftWSProducto.Producto>, SoftBodBusiness.SoftWSProducto.Producto {
        
        public ProductoClient() {
        }
        
        public ProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSProducto.eliminarProductoResponse SoftBodBusiness.SoftWSProducto.Producto.eliminarProducto(SoftBodBusiness.SoftWSProducto.eliminarProductoRequest request) {
            return base.Channel.eliminarProducto(request);
        }
        
        public int eliminarProducto(int productoId) {
            SoftBodBusiness.SoftWSProducto.eliminarProductoRequest inValue = new SoftBodBusiness.SoftWSProducto.eliminarProductoRequest();
            inValue.productoId = productoId;
            SoftBodBusiness.SoftWSProducto.eliminarProductoResponse retVal = ((SoftBodBusiness.SoftWSProducto.Producto)(this)).eliminarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.eliminarProductoResponse> SoftBodBusiness.SoftWSProducto.Producto.eliminarProductoAsync(SoftBodBusiness.SoftWSProducto.eliminarProductoRequest request) {
            return base.Channel.eliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.eliminarProductoResponse> eliminarProductoAsync(int productoId) {
            SoftBodBusiness.SoftWSProducto.eliminarProductoRequest inValue = new SoftBodBusiness.SoftWSProducto.eliminarProductoRequest();
            inValue.productoId = productoId;
            return ((SoftBodBusiness.SoftWSProducto.Producto)(this)).eliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSProducto.modificarProductoResponse SoftBodBusiness.SoftWSProducto.Producto.modificarProducto(SoftBodBusiness.SoftWSProducto.modificarProductoRequest request) {
            return base.Channel.modificarProducto(request);
        }
        
        public int modificarProducto(SoftBodBusiness.SoftWSProducto.productoDTO producto) {
            SoftBodBusiness.SoftWSProducto.modificarProductoRequest inValue = new SoftBodBusiness.SoftWSProducto.modificarProductoRequest();
            inValue.producto = producto;
            SoftBodBusiness.SoftWSProducto.modificarProductoResponse retVal = ((SoftBodBusiness.SoftWSProducto.Producto)(this)).modificarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.modificarProductoResponse> SoftBodBusiness.SoftWSProducto.Producto.modificarProductoAsync(SoftBodBusiness.SoftWSProducto.modificarProductoRequest request) {
            return base.Channel.modificarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.modificarProductoResponse> modificarProductoAsync(SoftBodBusiness.SoftWSProducto.productoDTO producto) {
            SoftBodBusiness.SoftWSProducto.modificarProductoRequest inValue = new SoftBodBusiness.SoftWSProducto.modificarProductoRequest();
            inValue.producto = producto;
            return ((SoftBodBusiness.SoftWSProducto.Producto)(this)).modificarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSProducto.insertarProductoResponse SoftBodBusiness.SoftWSProducto.Producto.insertarProducto(SoftBodBusiness.SoftWSProducto.insertarProductoRequest request) {
            return base.Channel.insertarProducto(request);
        }
        
        public int insertarProducto(SoftBodBusiness.SoftWSProducto.categoriaDTO categoria, string nombre, double precioUnitario, string unidadMedida, int stock, int stockMinimo, bool activo) {
            SoftBodBusiness.SoftWSProducto.insertarProductoRequest inValue = new SoftBodBusiness.SoftWSProducto.insertarProductoRequest();
            inValue.categoria = categoria;
            inValue.nombre = nombre;
            inValue.precioUnitario = precioUnitario;
            inValue.unidadMedida = unidadMedida;
            inValue.stock = stock;
            inValue.stockMinimo = stockMinimo;
            inValue.activo = activo;
            SoftBodBusiness.SoftWSProducto.insertarProductoResponse retVal = ((SoftBodBusiness.SoftWSProducto.Producto)(this)).insertarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.insertarProductoResponse> SoftBodBusiness.SoftWSProducto.Producto.insertarProductoAsync(SoftBodBusiness.SoftWSProducto.insertarProductoRequest request) {
            return base.Channel.insertarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.insertarProductoResponse> insertarProductoAsync(SoftBodBusiness.SoftWSProducto.categoriaDTO categoria, string nombre, double precioUnitario, string unidadMedida, int stock, int stockMinimo, bool activo) {
            SoftBodBusiness.SoftWSProducto.insertarProductoRequest inValue = new SoftBodBusiness.SoftWSProducto.insertarProductoRequest();
            inValue.categoria = categoria;
            inValue.nombre = nombre;
            inValue.precioUnitario = precioUnitario;
            inValue.unidadMedida = unidadMedida;
            inValue.stock = stock;
            inValue.stockMinimo = stockMinimo;
            inValue.activo = activo;
            return ((SoftBodBusiness.SoftWSProducto.Producto)(this)).insertarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSProducto.listarTodosProductosResponse SoftBodBusiness.SoftWSProducto.Producto.listarTodosProductos(SoftBodBusiness.SoftWSProducto.listarTodosProductosRequest request) {
            return base.Channel.listarTodosProductos(request);
        }
        
        public SoftBodBusiness.SoftWSProducto.productoDTO[] listarTodosProductos() {
            SoftBodBusiness.SoftWSProducto.listarTodosProductosRequest inValue = new SoftBodBusiness.SoftWSProducto.listarTodosProductosRequest();
            SoftBodBusiness.SoftWSProducto.listarTodosProductosResponse retVal = ((SoftBodBusiness.SoftWSProducto.Producto)(this)).listarTodosProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.listarTodosProductosResponse> SoftBodBusiness.SoftWSProducto.Producto.listarTodosProductosAsync(SoftBodBusiness.SoftWSProducto.listarTodosProductosRequest request) {
            return base.Channel.listarTodosProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.listarTodosProductosResponse> listarTodosProductosAsync() {
            SoftBodBusiness.SoftWSProducto.listarTodosProductosRequest inValue = new SoftBodBusiness.SoftWSProducto.listarTodosProductosRequest();
            return ((SoftBodBusiness.SoftWSProducto.Producto)(this)).listarTodosProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdResponse SoftBodBusiness.SoftWSProducto.Producto.obtenerProductoPorId(SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdRequest request) {
            return base.Channel.obtenerProductoPorId(request);
        }
        
        public SoftBodBusiness.SoftWSProducto.productoDTO obtenerProductoPorId(int productoId) {
            SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdRequest inValue = new SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdRequest();
            inValue.productoId = productoId;
            SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdResponse retVal = ((SoftBodBusiness.SoftWSProducto.Producto)(this)).obtenerProductoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdResponse> SoftBodBusiness.SoftWSProducto.Producto.obtenerProductoPorIdAsync(SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdRequest request) {
            return base.Channel.obtenerProductoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdResponse> obtenerProductoPorIdAsync(int productoId) {
            SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdRequest inValue = new SoftBodBusiness.SoftWSProducto.obtenerProductoPorIdRequest();
            inValue.productoId = productoId;
            return ((SoftBodBusiness.SoftWSProducto.Producto)(this)).obtenerProductoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosResponse SoftBodBusiness.SoftWSProducto.Producto.listarTodosConFiltroProductos(SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosRequest request) {
            return base.Channel.listarTodosConFiltroProductos(request);
        }
        
        public SoftBodBusiness.SoftWSProducto.productoDTO[] listarTodosConFiltroProductos(bool activo, string categoria, string nombreProducto) {
            SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosRequest inValue = new SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosRequest();
            inValue.activo = activo;
            inValue.categoria = categoria;
            inValue.nombreProducto = nombreProducto;
            SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosResponse retVal = ((SoftBodBusiness.SoftWSProducto.Producto)(this)).listarTodosConFiltroProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosResponse> SoftBodBusiness.SoftWSProducto.Producto.listarTodosConFiltroProductosAsync(SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosRequest request) {
            return base.Channel.listarTodosConFiltroProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosResponse> listarTodosConFiltroProductosAsync(bool activo, string categoria, string nombreProducto) {
            SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosRequest inValue = new SoftBodBusiness.SoftWSProducto.listarTodosConFiltroProductosRequest();
            inValue.activo = activo;
            inValue.categoria = categoria;
            inValue.nombreProducto = nombreProducto;
            return ((SoftBodBusiness.SoftWSProducto.Producto)(this)).listarTodosConFiltroProductosAsync(inValue);
        }
    }
}
