-- ============================================
-- SCRIPT DE LIMPIEZA Y REINICIALIZACIÓN
-- Base de Datos: TA_PROG3
-- ============================================

USE TA_PROG3;

-- Desactivar las restricciones de clave foránea temporalmente
SET FOREIGN_KEY_CHECKS = 0;

-- Limpiar todas las tablas (TRUNCATE = elimina registros y reinicia AUTO_INCREMENT)
TRUNCATE TABLE BOD_DETALLE_DEVOLUCION;
TRUNCATE TABLE BOD_DETALLE_VENTA;
TRUNCATE TABLE BOD_DEVOLUCION;
TRUNCATE TABLE BOD_HISTORIAL_OPERACIONES;
TRUNCATE TABLE BOD_PRODUCTO;
TRUNCATE TABLE BOD_CATEGORIA;
TRUNCATE TABLE BOD_CLIENTE_AL_FIADO;
TRUNCATE TABLE BOD_RAZON_DEVOLUCION;
TRUNCATE TABLE BOD_REGISTRO_PAGOS_FIADOS;
TRUNCATE TABLE BOD_USUARIO;
TRUNCATE TABLE BOD_VENTAS;
TRUNCATE TABLE BOD_VENTAS_FIADAS;

-- Reactivar las restricciones
SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- REINICIALIZACIÓN DE AUTO_INCREMENT
-- (en caso de que quieras asignar un valor específico)
-- ============================================
ALTER TABLE BOD_CATEGORIA AUTO_INCREMENT = 1;
ALTER TABLE BOD_CLIENTE_AL_FIADO AUTO_INCREMENT = 1;
ALTER TABLE BOD_USUARIO AUTO_INCREMENT = 1;
ALTER TABLE BOD_PRODUCTO AUTO_INCREMENT = 1;
ALTER TABLE BOD_RAZON_DEVOLUCION AUTO_INCREMENT = 1;
ALTER TABLE BOD_DEVOLUCION AUTO_INCREMENT = 1;
ALTER TABLE BOD_VENTAS AUTO_INCREMENT = 1;
ALTER TABLE BOD_HISTORIAL_OPERACIONES AUTO_INCREMENT = 1;
ALTER TABLE BOD_REGISTRO_PAGOS_FIADOS AUTO_INCREMENT = 1;
ALTER TABLE BOD_VENTAS_FIADAS AUTO_INCREMENT = 1;

-- Confirmar cambios
SELECT '✅ Limpieza y reinicio de índices completado.' AS Resultado;
